//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\David\Downloads\Minecraft-Deobfuscator3000-master\1.7.10 stable mappings"!

//Decompiled by Procyon!

package drealm.database;

import lotr.common.world.structure.*;
import net.minecraft.util.*;
import net.minecraft.item.*;
import lotr.common.*;
import net.minecraft.init.*;

public class DRChestContents
{
    public static LOTRChestContents RED_DWARF_HOUSE_LARDER;
    public static LOTRChestContents RED_MOUNTAINS_STRONGHOLD;
    public static LOTRChestContents RED_MOUNTAINS_SMITHY;
    
    static {
        DRChestContents.RED_DWARF_HOUSE_LARDER = new LOTRChestContents(2, 5, new WeightedRandomChestContent[] { new WeightedRandomChestContent(new ItemStack(Items.bread), 1, 3, 100), new WeightedRandomChestContent(new ItemStack(Items.cooked_porkchop), 1, 2, 75), new WeightedRandomChestContent(new ItemStack(Items.cooked_beef), 1, 2, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.muttonCooked), 1, 2, 75), new WeightedRandomChestContent(new ItemStack(Items.cooked_chicken), 1, 3, 75), new WeightedRandomChestContent(new ItemStack(Items.cooked_fished), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.gammon), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.deerCooked), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.mug), 1, 3, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.aleHorn), 1, 2, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.gobletWood), 1, 3, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.gobletGold), 1, 3, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.ceramicPlate), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.woodPlate), 1, 2, 50) });
        DRChestContents.RED_MOUNTAINS_STRONGHOLD = new LOTRChestContents(3, 5, new WeightedRandomChestContent[] { new WeightedRandomChestContent(new ItemStack(DRRegistry.helmetRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.bodyRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.legsRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.bootsRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.swordRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.spearRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.battleaxeRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.daggerRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.hammerRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.pikeRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.pickaxeRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.mattockRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.throwingAxeRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.boarArmorRedDwarven), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.coal), 1, 3, 100), new WeightedRandomChestContent(new ItemStack(Blocks.torch), 2, 4, 100), new WeightedRandomChestContent(new ItemStack(Items.iron_ingot), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.ironNugget), 1, 6, 25), new WeightedRandomChestContent(new ItemStack(DRRegistry.redDwarfSteel), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.mug), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.aleHorn), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.gobletWood), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(Items.cooked_porkchop), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(Items.cooked_chicken), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(Items.cooked_beef), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.muttonCooked), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(LOTRMod.deerCooked), 1, 1, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.gammon), 1, 1, 75), new WeightedRandomChestContent(new ItemStack(Items.compass), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.dwarvenRing), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.mithrilBook), 1, 1, 15) });
        DRChestContents.RED_MOUNTAINS_SMITHY = new LOTRChestContents(3, 4, new WeightedRandomChestContent[] { new WeightedRandomChestContent(new ItemStack(Items.coal), 1, 4, 100), new WeightedRandomChestContent(new ItemStack(Items.coal, 1, 1), 1, 4, 100), new WeightedRandomChestContent(new ItemStack(LOTRMod.rock, 1, 3), 1, 8, 50), new WeightedRandomChestContent(new ItemStack(Items.iron_ingot), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.ironNugget), 1, 6, 10), new WeightedRandomChestContent(new ItemStack(DRRegistry.redDwarfSteel), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.bronze), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.copper), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.tin), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.silver), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(Items.bucket), 1, 2, 50), new WeightedRandomChestContent(new ItemStack(Items.cooked_porkchop), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(Items.cooked_chicken), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(Items.cooked_beef), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.muttonCooked), 1, 4, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.gammon), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(LOTRMod.deerCooked), 1, 1, 25), new WeightedRandomChestContent(new ItemStack(Items.bread), 1, 3, 50), new WeightedRandomChestContent(new ItemStack(LOTRMod.mithrilBook), 1, 1, 15) });
    }
}
